### ISSUE TITLE
[Bug] app crashes while importing multiple photos

### ISSUE THREAD

**Issue by sivasren** [leonlatsch/Photok#104] opened 2021-04-26 08:50 UTC
Tried  to import around 400 photos through files app (com.google.android.documents.ui). Imported first 40-60 but then it crashed after I retried to import again it force closed again.
And secret launch code doesn't work.

I have S10e, One UI 3.1 Android 11. I didn't try on AOSP ROM if anyone has Samsung can you try import multiple photos?

**Comment by leonlatsch** [comment] 2021-04-27 10:19
Unfortunately I am not able to test this atm.
Import has been tested with 2000 photos before. I beleve it belongs to an error with a specific photo.

**Comment by leonlatsch** [comment] 2021-08-20 15:31
@sivasren Since I am not able to reproduce this, I will close this for now.

Feel free to reopen tough.

**Closed by leonlatsch** 2021-08-20 15:31 UTC
Labels: bug
