### ISSUE TITLE
Call number not working

### ISSUE THREAD

**Issue by Ezhurino** [leonlatsch/Photok#81] opened 2021-02-02 13:00 UTC
the code (*#*#1234#*#*) doesn't work on my phone, is there anything that i forgot?
i also checked the permissions and everything's good. am i missing something?
opening the app from the playstore or app settings doesn't work (guess that's a feature).
is there a way to open the app again without the number or deleting it? i didn't even get to make a backup :(

My pictures are important and i don't wanna lose em, i even deleted them from my phone completely( exept Photok)

**Comment by leonlatsch** [comment] 2021-02-02 14:37
You will have to launch it with `*#*#[code]#*#*` not `##[code]##`.

**Comment by leonlatsch** [comment] 2021-02-02 14:38
Btw. you can always test the launch code, since you can always launch it from the phone dialer, without hiding Photok.

**Comment by leonlatsch** [comment] 2021-02-02 19:24
Did it work?
If so, please close this :D

**Comment by Ezhurino** [comment] 2021-02-02 20:32
it didn't work, and i did it right, the app is already hidden (idiot me thought didn't think through to test the code first)
i can't open it from anywhere else on my phone since that just redirects me to my dialer.
this is how it looks like;
https://user-images.githubusercontent.com/76562252/106658653-d8699100-659d-11eb-81b0-87703f3194ed.mp4

**Comment by leonlatsch** [comment] 2021-02-02 21:04
Hmm, and you are 100% sure, this is your configured code?

**Comment by comparesheriff** [comment] 2021-02-02 21:08
Two ideas from my side:

1. Maybe for some reason it didn't fully save your custom code? Then it would still be the default (1337)
2. Another thing, that happened to me once: I deleted the default code and entered my own code. The field automatically fills with a zero as a default (because you can't have an empty code). So my new code was my code, with an added zero at the end. -> So you could try your code with an additional zero and see if that helps

If none of this helps, I believe it would be helpful if you could describe your phone setup, to make this reproducible (What vendor, which android version etc.)

**Comment by leonlatsch** [comment] 2021-02-02 22:54
You should try what @comparesheriff suggested.

**Comment by Ezhurino** [comment] 2021-02-03 15:10
yes, i'm 100% sure that's the code,
also @comparesheriff ideas didn't work;

https://user-images.githubusercontent.com/76562252/106766650-59766600-663a-11eb-8539-b33bec22b117.mp4


https://user-images.githubusercontent.com/76562252/106766658-5b402980-663a-11eb-94b1-ff9064c68647.mp4

**Comment by leonlatsch** [comment] 2021-02-03 15:29
I will set up an emulator for MIUI 12 and test if the code even works on MIUI. IF not, I will provide a hotfix for that.
If it works, we will need to search a little bit more :)

Also: What app version are you using and where did you get it from?

**Comment by leonlatsch** [comment] 2021-02-03 15:34
If you are fammiliar with adb, you could do a sysdump after entering the launchcode and post it here.

**Comment by leonlatsch** [comment] 2021-02-03 18:34
Tested on Xiaomi Mi9T Pro. Also not working.

Will provide a hotfix for that. Stay tuned :)

**Comment by leonlatsch** [comment] 2021-02-03 20:02
Found the issue. We will develop a way to fix this, but a workaround would be this:

In App Settings, open Other Permissions:
![image](https://user-images.githubusercontent.com/50983026/106802132-cf8ec300-6662-11eb-9dc3-903f4f9f03ff.png)

Then turn on this.
![image](https://user-images.githubusercontent.com/50983026/106802196-e7664700-6662-11eb-9270-f3fd0aec6b1c.png)

Worked in Xiaomi Mi9T Pro.

**Comment by leonlatsch** [comment] 2021-02-03 20:51
Since there is no way to check this setting, we will need to add a disclaimer describing this when hiding the app.
It will only show in Xiaomi.

**Comment by Ezhurino** [comment] 2021-02-03 22:55
i already looked through the settings before making this issue and found that, turned it on but nothing changed. i'll keep the app to be sure if somehow someday it fixed :). thanks for trying though

**Comment by leonlatsch** [comment] 2021-02-04 00:42
On out test device it worked after turning it on.

Maybe try what @comparesheriff suggested, with this option turned on.

**Comment by leonlatsch** [comment] 2021-02-04 17:51
@Ezhurino what version do you have and where did you get it from?

**Comment by fux0r2009** [comment] 2021-02-07 23:01
I also have a note 7 but not on MIUI just AOSP ROM and I don't have such a problem! just so you know it's MIU issue or (MIUI Version/Variant he is using)

**Comment by leonlatsch** [comment] 2021-02-07 23:06
@fux0r2009 We tested this on MIUI 12.0.4. He got 12.0.4.

On your device, it worked after turning popups on as showed. So we dont really know what to do next.

**Comment by fux0r2009** [comment] 2021-02-07 23:31
> @fux0r2009 We tested this on MIUI 12.0.4. He got 12.0.2.
> 
> On your device, it worked after turning popups on as showed. So we dont really know what to do next.

He needs to update his ROM (or better yet ditch MIUI but it's just my opinion) that's his most realistic option at least until some solution is found....

**Comment by leonlatsch** [comment] 2021-02-07 23:33
IF!, he got Photok from GitHub, I could provide a special apk to extract a backup or something. If not, its kind of impossible to get the data, without rooting the phone.

**Comment by leonlatsch** [comment] 2021-02-15 10:19
I will close this for now. Reopen if new informations are present.

**Closed by leonlatsch** 2021-02-15 10:19 UTC
Labels: bug, help wanted
