### ISSUE TITLE
Workaround to launch hid app while bypassing this message `Dialer: Not registered on network.`

### ISSUE THREAD

**Issue by Xyde** [leonlatsch/Photok#130] opened 2021-08-07 15:17 UTC
**Is your feature request related to a problem? Please describe.**
Secret code doesn't work with android devices not on a metered connection. Not sure if intended behavior or not.

**Describe the solution you'd like** **Describe alternatives you've considered**
Use the calculator to launch instead of dialer, or more thorough instructions on how to configurate the dialer.

**Comment by leonlatsch** [comment] 2021-08-13 15:14
For me the launch code works when turning off any internet connection.

Could you please describe a more detailed "steps to reproduce"?

**Comment by jerryn70** [comment] 2021-08-17 12:06
@leonlatsch dialing the serect code not opening the app what to do ? All my data is there. Turned off internet and tried but not opening. Pls help

**Comment by comparesheriff** [comment] 2021-08-17 12:21
@jerryn70 Sorry to hear that! Can you please provide more details to reproduce?

Phone (Brand + Version):
Android Version:
Dialer App:
Other relevant installed Stuff:

Steps to reproduce (How did you get there? Did you import Stuff first, or just enabled the secret code? Did it ever work or did it fail the first time? Did you change the code? What was your input in the dialer app?)

**Comment by jerryn70** [comment] 2021-08-17 12:52
@comparesheriff 

Device : Xiaomi redmi note 7 pro
Android version : 10
Dialer app : phones pre installed dialer ( i think xiaomi's own dialer app)

I just installed the app from fdroid and imported all my data, then set the secret pin and hide the app . After that I used dialer *#*#code#*#* but nothing happens . I tried so many times but the app was not opening.

**Comment by leonlatsch** [comment] 2021-08-17 12:59
Have you tried the right pattern?: `*#*#0000#*#*

**Comment by comparesheriff** [comment] 2021-08-17 13:00
@jerryn70 
Thank you for the quick response. Have you tried other hidden codes on your dialer yet?

For example on my device `*#*#225#*#*` gives the info of internal calendars.
You can have a look at [Hidden Codes on XDA](https://www.xda-developers.com/android-secret-codes/) to try some. Please report back if any dialer code works, so we can be sure that the dialer app is capable of opening these codes at all.

**Comment by jerryn70** [comment] 2021-08-17 13:01
#I found a temporary fix for those who are locked out by setting up secret pin.

1) Go to your phones gallery (if don't have and gallery app then download any gallery app from playstore)

2) Open any image

3) Then click the share button 

4) Choose photok app from the pop-up menu

5) Now the photok app will open and ask you for password

6) Type your password 

7) Now you have entered inside the app now you can go to the settings and disable 'hide app' option.

**Comment by leonlatsch** [comment] 2021-08-17 13:09
Thats one option 😅

**Comment by leonlatsch** [comment] 2021-08-17 13:10
> Thats one option 😅

Later today, I will add this to some FAQ or so.

Nevertheless we should think about how to handle these issues in the future.

**Comment by leonlatsch** [comment] 2021-08-17 15:33
I have an idea:
What about an option when hiding the app:

- When disabled the Photok icon just changes but still starts Photok normally
- When enabled the icon forwards to the phone dialer (like today)

Would be disabled by default.

**Comment by leonlatsch** [comment] 2021-08-17 15:37
> > Thats one option 😅
> 
> Later today, I will add this to some FAQ or so.
> 
> Nevertheless we should think about how to handle these issues in the future.

@jerryn70 @Xyde @comparesheriff https://github.com/leonlatsch/Photok/discussions/141

**Comment by leonlatsch** [comment] 2021-08-17 15:42
Since there is a workaround and a follow-up issue I will close this.

**Closed by leonlatsch** 2021-08-17 15:42 UTC
Labels: bug
