### ISSUE TITLE
It shows wrong thumbnail but correct full image when there are multiple images with same name

### ISSUE THREAD

**Issue by yasiralijaved** [leonlatsch/Photok#314] opened 2024-05-31 21:37 UTC
**Describe the bug**
It shows wrong thumbnail but correct full image when there are multiple images with same name.

**To Reproduce**
1. Import a photo of Tree with name photo.jpg into Photok
2. Open any file manager app and rename a file sky.jpg to photo.jpg
3. Now import that photo.jpg into Photok again. Note that it's now the picture of Sky.
4. The photok would display the thumbnails of both images as Tree. But when you click on them it would display correct images, Tree and Sky.

**Expected behavior**
If by clicking the thumbnails the photok shows correct images with same file names. The same should be case with the thumbnails too. It should display correct thumbnails of multiple files with same names.

**Screenshots**
N/A

**Smartphone:**
 - Device: Pixel 7a
 - OS: 14
 - Browser: N/A
 - Version Any version

**Additional context**
N/A

**Comment by leonlatsch** [comment] 2024-05-31 21:50
Will try to reproduce asap

**Comment by leonlatsch** [comment] 2024-06-01 07:37
Could not reproduce with 1.7.0. What version did you use?

**Comment by leonlatsch** [comment] 2024-06-05 20:35
closing for now, since it cannot be reproduced

**Closed by leonlatsch** 2024-06-05 20:35 UTC
Labels: bug, waiting for feedback
