### ISSUE TITLE
[Bug] *Importing from Android Sharing System imports every photo twice*

### ISSUE THREAD

**Issue by mschmidm** [leonlatsch/Photok#179] opened 2022-08-05 19:23 UTC
**Describe the bug**
When importing photos from the android sharing system, all photos get imported twice.

**To Reproduce**
1. Go to the phone photo gallery.
2. Select some photos (or only one)
3. Use the sharing system and choose Photok
4. The import dialog of photok already shows the double amount of pictures
5. Every photo gets imported twice

**Expected behavior**
Every photo should get imported only once.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A51
 - OS: Android 12
 - Version 1.3.5

Appeared also on another phone with Android 9.

Thank you for the app!

**Comment by leonlatsch** [comment] 2022-08-18 09:24
I will try to reproduce it soon.

Thank you.

**Comment by leonlatsch** [comment] 2022-08-18 15:55
Could not reproduce :/

**Comment by leonlatsch** [comment] 2022-08-24 19:28
Closing this for now, since I am not able to fix it.
If anybody is able to reproduce this, feel free to reopen :)

**Comment by mathix420** [comment] 2022-09-10 14:25
I have the same issue as well, I think I have identified when it occurs.
I am using Bitwarden on mobile, so after clicking share to Photok the password is prompted.

1. Sharing **ONE** picture to Photok.
2. Photok is opening and prompts for a password.
3. I click on the Bitwarden auto-fill utility
     ![picture](https://www.passageway.id/images/features/auto-fill-android/drawover.png)
4. It opens Bitwarden, I then click on the corresponding password to be filled-in in Photok
5. Bitwarden now closes and Photok login page is shown back again with the password filled-in
6. Log-in and Photok now tells me there are **TWO** pictures to import

I don't know exactly in which state goes your app during the Bitwarden auto-fill but it seems to be the source of this issue.
I also tried while copying the password so I don't need to go through the Bitwarden process, and the issue never occurred.

Thanks for this app, pretty good, I think it's the best opensource media lock out there!

**Comment by leonlatsch** [comment] 2022-09-10 14:27
> I have the same issue as well, I think I have identified when it occurs.
> 
> I am using Bitwarden on mobile, so after clicking share to Photok the password is prompted.
> 
> 
> 
> 1. Sharing **ONE** picture to Photok.
> 
> 2. Photok is opening and prompts for a password.
> 
> 3. I click on the Bitwarden auto-fill utility
> 
>      ![picture](https://www.passageway.id/images/features/auto-fill-android/drawover.png)
> 
> 4. It opens Bitwarden, I then click on the corresponding password to be filled-in in Photok
> 
> 5. Bitwarden now closes and Photok login page is shown back again with the password filled-in
> 
> 6. Log-in and Photok now tells me there are **TWO** pictures to import
> 
> 
> 
> I don't know exactly in which state goes your app during the Bitwarden auto-fill but it seems to be the source of this issue.
> 
> I also tried while copying the password so I don't need to go through the Bitwarden process, and the issue never occurred.
> 
> 
> 
> Thanks for this app, pretty good, I think it's the best opensource media lock out there!

Now this makes sense. Seems that the image is put into the list of images to be imported again when Bitwarden closes. 

I will reopen end try to reproduce it soon.

**Comment by leonlatsch** [comment] 2022-09-10 22:45
I will consider this as confirmed. Hard to reproduce without Bitwarden, but the code for this feature definitely has a flaw.

**Comment by leonlatsch** [comment] 2022-09-10 22:51
Tried a fix in #187 . Maybe someone is able to test it out. I could also provide a apk if you need one. Like I said, hard to reproduce for me :/

**Comment by mathix420** [comment] 2022-09-11 03:05
You can reproduce the same behavior by just showing the currently opened apps and then clicking back on Photok.
It seems to also be resuming the event and so duplicating all shared file.
If that still doesn't work on your side, I can try it myself with an APK.

**Comment by mschmidm** [comment] 2022-09-11 11:30
I am also using Bitwarden, this seems to be a cause. Showing the currently opened apps as @mathix420 suggested also leads to the bug for me. I can try the test myself with an APK too.

**Comment by leonlatsch** [comment] 2022-09-11 12:11
I tried reproducing with reopening from recent apps but it didn't occur. 

But makes sense that it occurs, so that might be on my side.

**Comment by leonlatsch** [comment] 2022-09-13 06:05
[debug-build.zip](https://github.com/leonlatsch/Photok/files/9553960/debug-build.zip)
Here is the debug apk for you to test it

**Comment by mschmidm** [comment] 2022-09-13 06:22
I tried the APK and the bug is gone. When using Bitwarden and when showing the recently used apps.
Although I noticed a slightly different behaviour than before: the import dialog "Do you want to import..." appears before one has entered the password. If one clicks "no" or _clicks outside_ of the dialog, it is hidden as espected but shown again after entering the password.
Before the dialog only appeared after entering the password.

Thank you for the quixk fix!

**Comment by leonlatsch** [comment] 2022-09-13 06:28
Nice. I will look into that again. But good to know that the bug is fixed.

**Comment by leonlatsch** [comment] 2022-09-15 15:29
So, again I cannot reproduce the opening of the dialog twice. For me it opens just as expected :/

**Closed** 2022-09-15 16:07 UTC
Labels: bug, selected for dev, confirmed

**Comment by leonlatsch** [comment] 2022-09-15 16:08
The fix for this is now merged and will be released anytime soon.

Thank you for the testing.
